### ISSUE TITLE
First Person or Third Person?

### ISSUE THREAD

**Issue by Gata-chan** [EricXu1728/Godot4SourceEngineMovement#7]
As Source is a First Person Shooter I expected this module to be as well, however when I open it in my editor it's third-person!

I am unsure if it's intentional since in Element Viewer the camera is postioned in First-Person perspective (pictured below):
![image](https://github.com/user-attachments/assets/9a7f95ca-43ef-4277-9a90-0e9e82342e35)

however when opening the project the perspective is from the third person (pictured below):
![image](https://github.com/user-attachments/assets/ef98233f-2ee8-41a8-86a5-0be4ec4f35a6)

While investigating I found that code metioned "spring" attachements (pictured below):
![image](https://github.com/user-attachments/assets/6d69022e-df4a-4512-9613-7a9bf98929a3)

which are characteristic of third person games and seems intentional.

Can you provide any clarification if this module is meant to be used in third or first person?

**Comment by EricXu1728** [comment]
It is supposed to be third person. You can make it 1st person by changing the player prefab by removing the spring component, adding back in the camera, and removing the related spring code.

Another solution would be to set the spring's length to 0. This is generally bad practice as I would recommend you edit to learn more of how godot works, but it will get you results.

You can edit this by finding player.tscn and editing it.
![image](https://github.com/user-attachments/assets/4d79e29c-93cc-4e7c-901e-3328cfb345a1)
![image](https://github.com/user-attachments/assets/09667a69-653d-4b8b-8ffb-12867bbdd416)

I would recommend learning more about how godot deals with prefabs and common components.
https://docs.godotengine.org/en/stable/classes/class_springarm3d.html
